#spring:
#    datasource:
#        driverClassName: org.postgresql.Driver
#        url: jdbc:postgresql://localhost:5432/postgres
#        username: postgres
#        password: Cherry
#        
#    jpa:
#        generate-ddl: true
#        show-sql: true
#        
#        hibernate:
#            ddl-auto: update
#            dialect: org.hibernate.dialect.PostgreSQLDialect